### ISSUE TITLE
[Feature?]: Icons R&D

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/tva#109]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Our goal is to provide icon resources in a way that enables our engineers to consistently create high-quality, performant applications.

To make an informed decision, we will be researching the differences in performance and quality, as well as the methods for achieving the highest level of each.

We will measure these by displaying icons in a plain react app (using `create-react-app`) using the following approaches:
- inline SVG
- icon font
- SVG as img src
- No SVGs (control)

Each test case will include a variety of icons and sizes, and will be the same with the exception of the icon implementation.

### Motivation 🔦

[An un-biased view on Icon fonts vs. SVG imports](https://github.com/pluralsight/tva/discussions/70)

**Comment by caseybaggz** [comment]
After findings, using SVG approach. Closing.
