### ISSUE TITLE
[Bug?]: HSL space-separated CSS syntax has some downstream issues

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/tva#145]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using the design tokens with storybook causes the whole storybook preview to break. I opened an [issue](https://github.com/styled-components/polished/issues/605) in what I think is the actual source of the issue, but I haven't gotten any response yet there.

### Expected behavior 🤔

The CSS values should be valid, and my browser agrees. Storybook is trying to do something with them via `polished` sometimes and that's what seems to break everything.

### Steps to reproduce 🕹

Steps:

1. Clone this repo: https://github.com/josh-degraw/hsl-issues and install dependencies
2. Run `npm run storybook` and see how storybook preview fails to load
3. Mess with the `colorSecondary` or `appContentBg` theme fields to see how using different syntax works differently

### Context 🔦

I wouldn't expect the syntax used by the tokens to cause problems. I don't know if this is just that new of a syntax or what, but I would expect that library to be able to handle the `hsl` syntax used. If other places have issues with this syntax, I discovered that using comma separated syntax seems to work just fine. I don't think this is necessarily the biggest issue in scope for this project, and the bug is outside of this codebase, but I wanted to at least bring it to your attention to see if there are any other potential issues like this.

**Comment by josh-degraw** [comment]
Relevant[storybook issue](https://github.com/storybookjs/storybook/issues/17619)

**Comment by caseybaggz** [comment]
Fix has been merged in styled-compoents. @josh-degraw after you guys upgrade, let me know if there are anymore issues you run across. 👍  Thanks so much for the contribution! 👏
