### ISSUE TITLE
[Bug?]: design tokens mobile assets not working

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/tva#318]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

All platforms of the mobile asset files from design-tokens are not using the correct token name or value. This works on all other platforms which mean is a bug in style-dictionary we need to find/fix in order to have tokens for our mobile teams.

### Expected behavior 🤔

Token asset naming and values should match web assets.

### Steps to reproduce 🕹

Steps:

1. Go into repo > packages > design-tokens > build-mobile
2. Look at all files
3. Names are using the token reference, not the name (i.e. not using ps-background), and the values are incorrect.

**Comment by Rykus0** [comment]
I think we need to store the tokens in a more universal format, then transform them into the desired output.  In this case, for web we can use the `color/hsl-4` transform.  The problem seems to be that the mobile transforms do not understand hsl-4 as an input.
