### ISSUE TITLE
[Docs?]: update Icons Web docs to be more useful

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/tva#325]
### Latest version

- [X] I have checked the latest version

### Summary 💡

The icon examples on the Usage (web) page are not as easy to consume/use as they could be. We need to do the following:

1. Show a live example for BasicExample
2. Update the basic code to *only* include icon content
3. Update basic full preview to *only* include a Icon component (i.e. remove "..." and "div" unless it's necessary to have it in the component - basically make the full preview copy/pastable for instant working in someone's app.
4. Add live example to Icon colors
5. Do all the same as #3
6. Add live example to Icon sizes
7. Change wording in "Importing by framework" section to "We export React components by default, ...". Then in the "other section - be specific to what other exports are available (i.e. svelte, svg)
8. Kill supported frameworks section
9. Kill importing SVG files - if something is marked "danger" in our docs - we should not be promoting it's use on the site.

**Comment by Rykus0** [comment]
@caseybaggz I'm on the fence about 9.  I agree if we've marked it as 'danger' that we should remove it.  But if we remove reference to this, then we remove (the knowledge of that) flexibility.  Maybe we take it out for now, and then add it back in if/when there's demand?
