### ISSUE TITLE
[Bug?]: Icons - xmlns missing from exported SVGs

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/tva#359]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using an SVG imported from the Icons package as the `src` for an `img` tag, the image is broken. 

### Expected behavior 🤔

The SVG should render when used as an img src.

### Steps to reproduce 🕹

https://codesandbox.io/s/basic-icons-mui-forked-hzmw7y?file=/src/App.tsx

Steps:

1. import any icon from the svg path
2. Assign the imported icon to the `src` attribute of an image

### Context 🔦

Want to provide the ability to import and use the SVGs regardless of framework.

### Your environment 🌎

```shell
https://codesandbox.io/s/basic-icons-mui-forked-hzmw7y?file=/src/App.tsx
```

**Comment by caseybaggz** [comment]
relates to #349 

Unfortunately, MUI requires this for the custom checkbox... 💀 
https://codesandbox.io/s/basic-mui-evcjvj?file=/src/App.tsx
