### ISSUE TITLE
[Feature?]: Add partial checked (minus) icon

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/tva#367]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add the 'minus' icon for the indeterminate state of multi-select checkbox controls.

### Examples 🌈

![image](https://user-images.githubusercontent.com/1745718/173602904-8c1adb06-e8e3-42ab-a6cc-983496fbc1ad.png)

**Comment by caseybaggz** [comment]
Feature merged. Closing.
