### ISSUE TITLE
[Bug?]: CSS Meta tokens do not have typescript type definitions

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/tva#507]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Meta tokens from #491 do not have typescript type definitions, so I can't reference them from typescript.

### Expected behavior 🤔

I should be able to import the js variables containing the css properties, but since there is no corresponding `.d.ts` file, typescript can't see them

### Steps to reproduce 🕹

Steps:

1. Try to import the meta variables

### Context 🔦

Trying to import the meta variables

### Your environment 🌎

```shell
`@pluralsight/design-tokens@0.0.0-experimental-3bcb66-20220817`
```

**Comment by caseybaggz** [comment]
@josh-degraw totally spaced on this. Temporarily, just do this until we get the types out:

```
declare module '@pluralsight/design-tokens/meta/cssProperties'
```

**Comment by caseybaggz** [comment]
@josh-degraw fix live onn `experimental`. Just upgrade to the latest one via

```
yarn up @pluralsight/design-tokens@experimental
```
