### ISSUE TITLE
[Feature?]: Expose a way to access individual CSS classes directly for JS usages

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/tva#740]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm working to integrate the TVA into our Skills Management Design System. I have previously prototyped integrating just the color tokens directly, but since there are many more headless styles available now I decided to try and integrate those more directly, and ran into some issues and I think I have a good solution that will help us be able to more tightly integrate the headless styles into our library. 

Basically I would like to be able to access the `components/{Component}/generated/{componentCSS}.module.ts` file directly.

### Motivation 🔦

In MUI V5, they offer a good API to tweak the global styles in a central location. We can define it in the theme definition like this:

```ts
const theme = createTheme({
  components: {
    MuiButton: {
      defaultProps: {
        disableRipple: true
      },
      styleOverrides: {
        root: ({theme, ownerState: props}) => ({ color: 'white'}),
        contained: {color: 'white', '&:hover': {color: 'red}},
        outlined: {},
        text: {},
        sizeLarge: {},
        sizeMedium: {},
        containedError: {},
        outlinedError: {},
        // ... etc.
      }
    }
}
```

And when doing it this way, for about 80% of the components in our library, we can then use the MUI components directly rather than redefining each of them explicitly.

This worked really well for just doing an inline update of our code from MUI v4 to MUI v5. 

And I could do something like this to integrate more directly with the headless styles package:

```ts
styleOverrides: {
    root: getJSButtonProps().button.styles,
    outlined: getJSButtonProps({ usage: 'outline' }).button.styles,
    // etc.
}
```

But due to the combinatorial nature of the styles (e.g. `usage x sentiment x size` etc), doing it this way would result in some unpredictable style declaration conflicts due to multiple styles being included in each kind of call.

I could also do it more dynamically e.g. something like :

```ts
styleOverrides: {
    root({
      ownerState: {
        size = 'medium',
        variant = 'contained'
      }
    }){
        const sizeMap: Partial<Record<typeof size, ButtonOptions['size']>> = {
          large: 'l',
          medium: 'm'
        }
        const usageMap: Record<typeof variant, ButtonOptions['usage']> = {
          text: 'text',
          outlined: 'outline',
          contained: 'filled'
        }

        return getJSButtonProps({usage: usageMap[variant], size: sizeMap[size]}).button.styles
    }
}
```

But that still leads to some issues both with developer ergonomics on my end (e.g. mapping `variant` to `usage` etc.) and with styles (some style declarations are overwritten by MUI due to declaration order).

If I were able to access the already generated `buttonCSS.module.ts`, I could do something like this and it would map very cleanly to the way it works in MUI already without applying anything redundant.

```ts
import buttonCss from '@pluralsight/components/Button/generated/buttonCSS.module'

createTheme({
  components: {
    styleOverrides: {
        root: buttonCss.btnBase,
        contained: buttonCss.filledButton,
        outlined: buttonCss.outlineButton,
        text: buttonCss.textButton,
        sizeLarge: buttonCss.lButton,
        sizeMedium: buttonCss.mButton,
        // ... etc.
      }
    }
  }
})
```

We could then do this for any component that maps 1:1 to a `headless-style` component and it would dramatically reduce the amount of work we'd need to do on our end to keep our styles in sync.

**Comment by caseybaggz** [comment]
Ah, interesting and great find @josh-degraw ! This will require a little bit of work now that we are bundling, but it should be more on the (unfortunate) package.json exports field side.

If you are familiar with Rollup, you are more than welcome to submit a PR with the updates to get it out faster? If not, give me a week or so and we can squeeze this into the Beta release (originally next Monday).
