### ISSUE TITLE
[Bug?]: CSS Pseudo selectors incorrectly transformed

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/tva#818]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Looks like there are some transformations that are used to make the CSS work with JSX that break Pseudoselectors: 

```
Warning: Unsupported style property &:focus:not(:focus-visible) + .checkboxControl. Did you mean &:focus:not(:focusVisible) + .checkboxControl?
```

### Expected behavior 🤔

Pseudo-selectors such as `:focus-visible` should not be changed to `:focusVisible`.

### Steps to reproduce 🕹

Steps:

1. Use `getJSCheckboxProps` with MUI@5.10.12

### Context 🔦

Just trying to test out integrating headless styles with Skills Management design system

**Comment by Rykus0** [comment]
@josh-degraw Do you have a code snippet you could share?  I was having a hard time duplicating it in our codesandbox instance.  I think I've just about got it fixed, but want to be sure.
