### ISSUE TITLE
[Enhancement]: Improved type name output

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/tva#856]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

There are currently many different type declarations with the same name (e.g. `Kind`, `Size`, etc.). This results in the type name being modified in the generated `.d.ts` files:

```ts
/// CircularProgress/types.ts
export interface CircularProgressOptions extends CircularProgressA11yOptions {
  kind?: Kind
  size?: Size
  tech?: Tech
}

export type Kind = 'determinate' | 'indeterminate'
export type Size = 'xs' | 'm'

/// Generated types:
interface CircularProgressOptions extends CircularProgressA11yOptions {
    kind?: Kind$4;
    size?: Size$6;
    tech?: Tech;
}
declare type Kind$4 = 'determinate' | 'indeterminate';
declare type Size$6 = 'xs' | 'm';
```

It would provide a bit better end-user experience to name these in a way that the names don't clash:

```ts
export interface CircularProgressOptions extends CircularProgressA11yOptions {
  kind?: CircularProgressKind
  size?: CircularProgressSize
  tech?: Tech
}

export type CircularProgressKind = 'determinate' | 'indeterminate'
export type CircularProgressSize = 'xs' | 'm'
```

In the same vein, it would be very helpful to have those types exported by the library. For example, currently there's no way to import `CircularProgressOptions` directly (as far as I know). I currently can only get that type via:
```ts
type CircularProgressOptions = NonNullable<
  Parameters<typeof getJSCircularProgressProps>[0]
>
```

Renaming these commonly used types would also make it easier to expose these because then it would be possible to just `export * from './components/CircularProgress'`, for example, without worrying about name collisions.

**Comment by caseybaggz** [comment]
@josh-degraw great feedback! For now, we actually do export all the types at the `/types` path. 👍 

See Example here:
https://design.pluralsight.com/docs/development/headless-styles/CircularProgress#circularprogressoptions
