### ISSUE TITLE
[Bug?]: headless-styles isn't tree-shakeable

### ISSUE THREAD

**Issue by ThatJoeMoore** [pluralsight/tva#940]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

See https://github.com/ThatJoeMoore/ps-tva-building for example build code.

When building a simple bundle which only uses Button and FieldMessage, the entire headless-styles package gets included in the output.

Input:

```js
import { getButtonProps, getFieldMessageProps, getJSButtonProps, getJSFieldMessageProps } from "@pluralsight/headless-styles"

console.log({
  css: {
    button: getButtonProps(),
    fieldMessage: getFieldMessageProps()
  },
  js: {
    button: getJSButtonProps(),
    fieldMessage: getJSFieldMessageProps()
  }
})
```

Minified output sizes built with Webpack, Rollup, and esbuild:

```
251K headless-styles-esbuild.js
253K headless-styles-rollup.js
158K headless-styles-webpack.js
```

If you inspect the output bundles, the CSS for all of the components is included, unminified, and with inline source maps.

### Expected behavior 🤔

Only the CSS/JS that is actually used should be included in the output bundle.

### Steps to reproduce 🕹

Steps:

1. Clone https://github.com/ThatJoeMoore/ps-tva-building
2. Run `yarn build:minify` to get minified bundles. Or, run `yarn build` to get the unminified, easer-to-inspect version.

### Context 🔦

Having worked with a similar design system package in the past, I've got some recommendations (which I will submit as a PR shortly).

Most of these recommendations basically boil down to the differences between a library and an application, and work on the assumption that, if a consumer wants something like minification, it'll take care of it at that level. Often times 'production' app-style optimizations have negative impacts in a library, as it prevents the consumer from making smarter, use-case specific optimizations (like tree-shaking).

1) By outputting a single output file with all of the components, downstream projects cannot tree-shake the component CSS, as the `style-inject` pieces are not side-effect free. This can be resolved by using `preserveModules: true` in the rollup config, as this keeps the files separate, and the `sideEffects: false` setting in `package.json` works properly. Basically, the tree-shakers will keep EVERYTHING that has side effects inside a file that gets anything used, as they can't tell which parts are used for what, so splitting up the files allows the tree shaker to see what CSS is used and what isn't.

2) It's worth it to always minify CSS that's getting injected into JS - not minifying it doesn't actually make anything more readable (since it's always shoved into a JS string), it just makes it take up more space.

3) In spite of literally weeks trying, I've never gotten sourcemaps to work properly with CSS that's injected into JS by the postcss plugin. Since they don't help with anything anyway, it's worth it to just not generate them, as the inline comment is quite large and can't be minified/tree-shaken.

4) In a library, there really isn't a point to doing minification. Consumers should be expected to do such optimizations themselves. This makes the library a lot simpler by getting rid of the need to have dev/prod builds and switches between them (which don't typically work without help in bundlers - looking at you, `process.env` 🤨 )

So, some concrete proposals:

1) Set `preserveModules: true` for the source Rollup config (which requires pointing the output at a directory)
2) Always minify injected styles and disable source maps in the postcss plugin.
3) Remove development versions of the code bundles and produce a single artifact.

Implementing these changes, the same build as above results in these sizes, which only includes code related to the components which are actually imported:

```
8.4K headless-styles-esbuild.js
8.1K headless-styles-rollup.js
8.1K headless-styles-webpack.js
```

**Comment by caseybaggz** [comment]
@ThatJoeMoore looks like the PR we merged broke all the imports so I had to revert it via [#943](https://github.com/pluralsight/tva/pull/943). I have basic sandboxes that tested it. For some reason, Codesandbox CI really doesn't like rollup, but I'll see if we can get it building PRs again with HS.

Looking forward to seeing a working solution to this and hope we can get it working.

**Comment by ThatJoeMoore** [comment]
Hmm. Interesting. I know a couple more rollup knobs we can try, which are more work but would let us control the name of the style-inject bundle. I'll see if I can't get that implemented today.

**Comment by caseybaggz** [comment]
@ThatJoeMoore I just merged a PR that now adds HS to the CI PR preview build so we can test it in the next PR submitted. 😄
